on:
  push:
    branches: [master]
    paths-ignore:
      - '*.md'
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run the action on a test graph and publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build graph's SPA
        uses: logseq/publish-spa@main
        with:
          graph-directory: /
          theme-mode: dark
          accent-color: cyan

      - name: Add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
